HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-x86_64
  agent:
    roles:
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-x86_64
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
