source "https://rubygems.org"

# C Ruby (MRI) or Rubinius, but NOT Windows
platforms :ruby do
  gem 'pry', :group => :development
  gem 'yard', :group => :development
  gem 'redcarpet', '~> 2.0', :group => :development
end

gem "puppet", :path => "..", :require => false
gem "puppet-test", :path => '../puppet-test', :require => false
gem "rake", :require => false
gem "rgen", "0.6.5", :require => false

group(:development, :test) do
  # Jenkins workers may be using RSpec 2.9, so RSpec 2.11 syntax
  # (like `expect(value).to eq matcher`) should be avoided.
  gem "rspec", "~> 2.11.0", :require => false

  # Mocha is not compatible across minor version changes; because of this only
  # versions matching ~> 0.10.5 are supported. All other versions are unsupported
  # and can be expected to fail.
  gem "mocha", "~> 0.10.5", :require => false

  gem "yarjuf", "~> 1.0"

  # json-schema does not support windows, so use the 'ruby' platform to exclude it on windows
  platforms :ruby do
    # json-schema uses multi_json, but chokes with multi_json 1.7.9, so prefer 1.7.7
    gem "multi_json", "1.7.7", :require => false
    gem "json-schema", "2.1.1", :require => false
  end
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end

# vim:filetype=ruby
